### ISSUE TITLE
FIX: allow for args

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/SHED#44]
Some functions just won't do `**kwargs` so we need a syntax for providing args. This may end up a bit tricky as we need to not only map data from the events into args but also from `*args` provided in the init of the stream. We can provide the `args` positions as keys in the `input_info` dict as integers are not valid keys in a function.
Potential fixes pieces:
1. `input_info = {0: 'img', 'I0': 'I0'}` This maps the data in the `img` key to the 0th position in args yielding `func('img', 'I0')`
1. `input_info = {0: 'img', 1: 'I0'}` with `args=('b', )` we assume that we can fill any missing args positions from the `input_info` with stuff from the stream `args` thus `func('img', 'b', 'I0')`. Note that this means we must have at least as many `args` provided as there are gaps in our `input_info`. If `input_info = {0: 'img', 10: 'temperature'}` we better have at least 9 things in `args`.

@ordirules @danielballan thoughts?

**Comment by ordirules** [comment]
Yes, taking in args would be great :-). I have two main questions/comments about this.

*First*: Why:
```
input_info = {0: 'img', 'I0': 'I0'}
```
and not
```
input_info = {'img': 0, 'I0': 'I0'}
```
I feel for inputs, `from : to` seems to logcally flow better than `to : from` in a mapping.

*Second* : I would vote not explicitly putting number positions for the args. In the same way when calling a function we don't expliticlty write the position the arg should be in the function, maybe we should do same here. I'd vote making `input_info` a tuple of mappings, so:
```
input_info = ( ('img', None), ('I0', 'I1'), 'a' )
```
Here, the first tuple `('img', None)` means map `img` to a non-`kwarg` (so it becomes an `arg`), map `I0` to `I1`, and finally map `a` into `a`. For the last, a tuple is not needed since that is pretty clear.
That's what we used for our streams, and it may not necessarily be the best method. (Basically [here](https://github.com/CFN-softbio/SciStreams/blob/master/SciStreams/interfaces/StreamDoc.py#L267))

However, I'm open to other alternatives.

**Comment by CJ-Wright** [comment]
To your first question:
The positions/function key word arguments are guaranteed to be unique. The inputs are not. Eg I want to subtract two images, they are both called `pe1_image`.

**Comment by CJ-Wright** [comment]
Note that we also need to address which stream we are getting the data from. Currently this is handled by an optional addition to the `input_info`. `map(subs, zip(a, b), input_info={'img1': ('pe1_image', 0), 'img2': ('pe1_image', 1)})` This states that img1 is obtained from the first stream and img2 from the second.

**Comment by CJ-Wright** [comment]
We are going to assume that the function signature allows for stream args first and then *args from the init second followed by stream/init kwargs. Switch dict key values. Args are referenced via numbers in values in dict.

**Comment by CJ-Wright** [comment]
Just to encapsulate a conversation with @ordirules 
Python functions guarantee that the names of args/kwargs are unique. Dicts make the same guarantee with their keys. The data that goes into those args/kwars are not guaranteed to be unique. Eg (a function which calculates the correlation between two plots could be used as an auto-correlation if we plug the same data set in twice). Thus, the data can't serve as a key for a dict.

**Comment by CJ-Wright** [comment]
Here are the cases I think we need to cover:

| Cases | args | kwargs| args and kwargs|
| ---------- |:-------:|:-----------:|:----------------------:|
| event only| | X | |
| init only | | X | |
| event and init | | X | |
